# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mobiliz Ar-Ge Blog!
email: argeblog@mobiliz.com.tr
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/my-jekyll" # the subpath of your site, e.g. /blog
url: "http://mobiliz.com.tr" # the base hostname & protocol for your site
twitter_username: fsonmezay
github_username:  fsonmezay
# logo-img: http://ferdisonmezay.com/2015/images/logo.png
# logo-text: FERDİ SÖNMEZAY
# logo-text-small: Free Software, Software Craftsmanship, Photography
logo-img: http://www.mobiliz.com.tr/img/mobiliza-logo.png
logo-text: < /code >
logo-text-small:
logo-width: 115

# Build settings
markdown: kramdown
